config/routes.rb
Rails.application.routes.draw do
  root 'flights#search'
  resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :arrivals, class_name: 'Flight', foreign_key: 'destination_id'
  has_many :departures, class_name: 'Flight', foreign_key: 'origin_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin, class_name: "Airport"
  belongs_to :destination, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings
  before_save :add_duration

  def add_duration
    time_delta = arrival_time - departure_time
    self.duration = "#{(time_delta / 3600).to_i.abs}h#{(time_delta % 3600 / 60).to_i}m"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  validates :name, :email, presence: true

  belongs_to :booking
  has_one :flight, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    passenger_number = params[:number].to_i
    passenger_number.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking
    else
      redirect_to root_url
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,
                                    :date,
                                    passengers_attributes: %i[id name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def search
    # Options for select
    @flight = Flight.new
    @airports = Airport.select('code, id').map { |i| [i.code, i.id] }

    # Search results
    if params[:origin_id] && params[:destination_id]
      @flights = Flight.where(origin_id:      params[:origin_id],
                              destination_id: params[:destination_id])
      @flights = @flights.paginate(page: params[:page], per_page: 10)
      @search_params = { date: date_params, number: params[:number] }
    else
      @flights = Flight.all.paginate(page: params[:page], per_page: 15)
      @search_params = { date: { day: Date.today.day, month: Date.today.month, year: Date.today.year }, number: 1 }
    end
  end

  def date_params
    params.require(:date).permit(:day, :month, :year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_booking.html.slim
div.subtitle.is-size-4 Flight #{@flight.number}
div.is-size-5 Leaving #{@flight.origin.code} at #{@flight.departure_time.strftime("%I:%M %p")}
div.is-size-5 Arriving in #{@flight.destination.code} at #{@flight.arrival_time.strftime("%I:%M %p")}
div.is-size-5 Duration: #{@flight.duration}

app/views/bookings/new.html.slim
div.container
  div.columns
    div.column
      h1.title New Booking
      = render @booking

    div.column

      = form_for @booking do |booking_form|
        = booking_form.hidden_field :flight_id, value: params[:flight_id]

        div.field
          = booking_form.label :departure_date
          div.control
            = booking_form.date_select :date, { order: [:month, :day, :year], default: params[:date] },
                                              { class: :select }

        - i = 0
        = booking_form.fields_for :passengers do |passenger_fields|
          p.label Passenger #{i += 1}
          
          div.field
            = passenger_fields.label :name
            div.control
              = passenger_fields.text_field :name

          div.field  
            = passenger_fields.label :email
            div.control
              = passenger_fields.text_field :email

          div.field
            div.control
              = booking_form.submit

app/views/bookings/show.html.slim
div.container

  h1.title Booking

  div.columns
    div.column
      = render @booking

    div.column
      div.label Passengers:
      - @passengers.each do |passenger|
        div.name = passenger.name

app/views/flights/_flight.html.slim
tbody
  tr
    th = link_to flight.number, new_booking_path(@search_params.merge({ flight_id: flight.id }))
    td = flight.origin.code
    td = flight.destination.code
    td = flight.departure_time.strftime("%I:%M %p")
    td = flight.duration
    td = flight.arrival_time.strftime("%I:%M %p")

app/views/flights/search.html.slim
div.container
  div.columns
    div.column
      = form_tag '/', method: 'get'

      div.field
      = label_tag :from, nil, class: 'label'
      div.control
        = select_tag :origin_id, options_for_select(@airports), class: :select

      div.field
      = label_tag :to, nil, class: 'label'
      div.control
        = select_tag :destination_id, options_for_select(@airports), class: :select

      div.field
      = label_tag :passengers, nil, class: 'label'
      div.control
        = select_tag :number, options_for_select((1..4)), class: :select

      div.field
      = label_tag :date, nil, class: 'label'
      div.control
        = select_date Date.today,
                    { order: %i[month day year], start_year: Date.today.year },
                    { class: :select }

      br

      div.field.is-grouped
        div.control
          = submit_tag :search, class: 'button is-primary'
        div.control
          = link_to 'reset', root_url, class: 'button'

    div.column
      - if @flights.any?
        table.table
          thead
            th Flight
            th Origin
            th Destination
            th Departure
            th Duration
            th Arrival
          = render @flights
      - else
        p No flights found.
        
      = will_paginate @flights

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <br>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.slim
section.hero.is-info.is-bold
  div.hero-body
    div.container
      h1.title = link_to 'FlightBooker', root_url
      h2.subtitle Search for flights

app/views/shared/_navbar.html.slim
nav.navbar
  div.navbar-brand
    = link_to 'FlightBooker', root_url, class: 'navbar-item'